#docker-compose -f docker-compose.prod.yml build
#docker-compose -f docker-compose.prod.yml up
#docker-compose -f docker-compose.prod.yml down -v --remove-orphans

version: '3.7'

services:
    templatebackend_housing:
        container_name: templatebackend_housing
        ports:
            - 3001:3001
        build:
            context: .
            dockerfile: Dockerfile.prod
        networks:
            - backendnetwork
        depends_on:
            - redis
        env_file:
            - .env
    redis:
        container_name: redis_container
        image: redis:5
        volumes:
            - type: volume
              source: redis
              target: /data
        networks:
            - backendnetwork
    mariadb:
        image: 'mariadb:10'
        restart: always
        volumes:
            - type: volume
              source: db
              target: /var/lib/mysql
        env_file:
            - '.env'
        networks:
            - backendnetwork
    nginx:
        image: nginx:mainline-alpine
        container_name: nginx
        volumes:
            - ./nginx.prod.conf:/etc/nginx/nginx.conf
        networks:
            - backendnetwork
        ports:
            - 80:80
        depends_on:
            - templatebackend_housing

networks:
    backendnetwork:

volumes:
    db:
    redis:
